// File generated by FlutterFire CLI.
// Run `flutterfire configure` after creating your Firebase project to replace
// these placeholder values with your real project configuration.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'formation-go',
    authDomain: 'formation-go.firebaseapp.com',
    storageBucket: 'formation-go.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9k80emKBIwtziFtqjjod42Q-qQPK-kmM',
    appId: '1:291642320864:android:082e5be4561a1ea80c2d85',
    messagingSenderId: '291642320864',
    projectId: 'formation-go',
    storageBucket: 'formation-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'formation-go',
    storageBucket: 'formation-go.appspot.com',
    iosBundleId: 'com.example.formationGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'formation-go',
    storageBucket: 'formation-go.appspot.com',
    iosBundleId: 'com.example.formationGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'formation-go',
    authDomain: 'formation-go.firebaseapp.com',
    storageBucket: 'formation-go.appspot.com',
  );
}
